// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260126143040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<int>("StokMiktari")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Apple Watch 7",
                            AktifMi = false,
                            Fiyat = 10000m,
                            StokMiktari = 10
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Apple Watch 8",
                            AktifMi = true,
                            Fiyat = 20000m,
                            StokMiktari = 50
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Apple Watch 9",
                            AktifMi = true,
                            Fiyat = 30000m,
                            StokMiktari = 30
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Apple Watch 10",
                            AktifMi = false,
                            Fiyat = 40000m,
                            StokMiktari = 20
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Apple Watch 11",
                            AktifMi = true,
                            Fiyat = 50000m,
                            StokMiktari = 0
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Apple Watch 12",
                            AktifMi = true,
                            Fiyat = 60000m,
                            StokMiktari = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
