// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260126192327_UpdateUrunEntity")]
    partial class UpdateUrunEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fiyat")
                        .HasColumnType("REAL");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit aliquid dolores magni in unde sint fugiat nobis eveniet, culpa molestiae? Quam quasi quia nobis placeat facere hic harum unde! Facilis.",
                            Ad = "Apple Watch 7",
                            AktifMi = false,
                            Anasayfa = true,
                            Fiyat = 10000.0,
                            Resim = "1.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit aliquid dolores magni in unde sint fugiat nobis eveniet, culpa molestiae? Quam quasi quia nobis placeat facere hic harum unde! Facilis.",
                            Ad = "Apple Watch 8",
                            AktifMi = true,
                            Anasayfa = true,
                            Fiyat = 20000.0,
                            Resim = "2.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit aliquid dolores magni in unde sint fugiat nobis eveniet, culpa molestiae? Quam quasi quia nobis placeat facere hic harum unde! Facilis.",
                            Ad = "Apple Watch 9",
                            AktifMi = true,
                            Anasayfa = true,
                            Fiyat = 30000.0,
                            Resim = "3.jpeg"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit aliquid dolores magni in unde sint fugiat nobis eveniet, culpa molestiae? Quam quasi quia nobis placeat facere hic harum unde! Facilis.",
                            Ad = "Apple Watch 10",
                            AktifMi = false,
                            Anasayfa = false,
                            Fiyat = 40000.0,
                            Resim = "4.jpeg"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit aliquid dolores magni in unde sint fugiat nobis eveniet, culpa molestiae? Quam quasi quia nobis placeat facere hic harum unde! Facilis.",
                            Ad = "Apple Watch 11",
                            AktifMi = true,
                            Anasayfa = true,
                            Fiyat = 50000.0,
                            Resim = "5.jpeg"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit aliquid dolores magni in unde sint fugiat nobis eveniet, culpa molestiae? Quam quasi quia nobis placeat facere hic harum unde! Facilis.",
                            Ad = "Apple Watch 12",
                            AktifMi = true,
                            Anasayfa = false,
                            Fiyat = 60000.0,
                            Resim = "6.jpeg"
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit aliquid dolores magni in unde sint fugiat nobis eveniet, culpa molestiae? Quam quasi quia nobis placeat facere hic harum unde! Facilis.",
                            Ad = "Apple Watch 13",
                            AktifMi = false,
                            Anasayfa = false,
                            Fiyat = 70000.0,
                            Resim = "7.jpeg"
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sit aliquid dolores magni in unde sint fugiat nobis eveniet, culpa molestiae? Quam quasi quia nobis placeat facere hic harum unde! Facilis.",
                            Ad = "Apple Watch 14",
                            AktifMi = true,
                            Anasayfa = true,
                            Fiyat = 80000.0,
                            Resim = "8.jpeg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
